services:
  - type: web
    name: medicine-reminder-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: medicine_reminder_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: medicine_reminder_db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: medicine_reminder_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: medicine_reminder_db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: medicine_reminder_db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://medicine-reminder-frontend.onrender.com
      - key: PORT
        value: 10000

databases:
  - name: medicine_reminder_db
    databaseName: medicine_reminder
    user: medicine_reminder_user
    plan: free 